name: suzuki
channels:
  - annaconda
  - conda-forge
  - temporary-recipes
dependencies:
  - autopep8=1.4.4
  - boto3=1.9.10
  - cython=0.28.5
  - distance=0.1.3
  - fastdtw=0.3.2
  - feather-format=0.4.0
  - gensim=3.6.0
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions=0.5.1
  - luigi=2.7.8
  - matplotlib=3.1.0
  - mecab-python3=0.7
  - minepy=1.2.4
  - nb_conda=2.2.1
  - numpy=1.15.2
  - pandas=0.24.0
  - pandas-profiling=1.4.2
  - pip=19.1
  - plotnine=0.5.1
  - progressbar=2.5
  - psycopg2=2.7.6.1
  - pyknp=0.4.1
  - pystan=2.18.0.0
  - python=3.6.8
  - scikit-learn=0.19.2
  - sciluigi=0.9.6b7
  - scipy=1.1.0
  - seaborn=0.9.0
  - sqlalchemy=1.2.12
  - sqlite=3.28.0
  - statsmodels=0.9.0
  - tqdm=4.31.1
  - xlrd=1.2.0
  - xlsxwriter=1.1.1
