image: nexus.support.data-lab.io:8082/thinkbiganalytics/r-base

before_script:
  - apt-get update -qq  && apt-get -y --no-install-recommends install gsl-bin libgsl0-dev curl
  - install2.r --deps TRUE --error xts
  - installGithub.r jpmml/r2pmml && rm -rf /tmp/downloaded_packages/
  - R -e 'install.packages("dmmfR", repos=c("https://nexus.support.data-lab.io/repository/dslab-r", getOption("repos")), dependencies = TRUE)'

build_test_deploy: 
   script:
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-manual --no-vignettes
    - curl -v --user ${NEXUS_REGISTRY_USER}:${NEXUS_REGISTRY_PASSWORD} --upload-file ${PKG_FILE_NAME} https://nexus.support.data-lab.io/repository/dslab-r/src/contrib/${PKG_FILE_NAME}
    - rm -r ${PKG_FILE_NAME}
   only:
    - master

build_test:
   script:
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-manual --no-vignettes
    - rm -r ${PKG_FILE_NAME}
   except:
    - master
